# Generated by Django 6.0.7 on 2026-08-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_type', models.CharField(choices=[('advisor', 'Advisor'), ('hod', 'Head of Department'), ('fyp_coordinator', 'FYP Coordinator'), ('scholarship_coordinator', 'Scholarship Coordinator'), ('internship_coordinator', 'Internship Coordinator'), ('exam_officer', 'Examination Officer'), ('finance_officer', 'Finance Officer'), ('student_affairs_officer', 'Student Affairs Officer')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='accounts.facultyprofile')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['responsibility_type'],
            },
        ),
    ]
