# Generated by Django 6.0.7 on 2026-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='required_responsibility',
            field=models.CharField(blank=True, choices=[('advisor', 'Advisor'), ('hod', 'Head of Department'), ('fyp_coordinator', 'FYP Coordinator'), ('scholarship_coordinator', 'Scholarship Coordinator'), ('internship_coordinator', 'Internship Coordinator'), ('exam_officer', 'Examination Officer'), ('finance_officer', 'Finance Officer'), ('student_affairs_officer', 'Student Affairs Officer')], max_length=50, null=True),
        ),
    ]
