# Generated by Django 6.0.7 on 2026-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_workflowstep_required_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded'), ('revision_required', 'Revision Required'), ('resubmitted', 'Resubmitted')], max_length=30),
        ),
    ]
